version: "3.1"

services:
  db:
    image: mysql:5.7.27
    ports:
      - "4000:3306"
    environment:
      MYSQL_USER: pwauser
      MYSQL_ROOT_PASSWORD: pwa123
      MYSQL_PASSWORD: pwa123
      MYSQL_DATABASE: pwa2021
    volumes:
      - ./mysqldata:/var/lib/mysql

  app:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
    environment:
      DDBB_NAME: pwa2021
      DDBB_HOST: db
      DDBB_USER: pwauser
      DDBB_PASSWORD: pwa123
      PRODUCCION: 0
    ports:
      - 8000:80

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pwa123
    ports:
      - 8001:80
